apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: p9yevbn3i-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:6e3e89158579cb5e16c3386b4318ab2fb642fcdc@sha256:366246d9f2a46cf2d1fbe5d67449da8ecb35f6471193917d8ec4d3608cb8f763
          name: container-image
